Add Subscription Service API
Dulwich-Bookings/Dulwich-Bookings-Frontend pull request #22
Opened 2022-06-15 16:27 UTC by elizabethhky

## Changes
- Add Modules
  - subscription
- Add SubscriptionService API
 
## Testing
- Click on buttons 'Create Subscription', 'Get All Subscriptions' etc. underneath Subscription section on the tests page
- Created dummy data in Test page

## Issues
- Resolves #20

2022-06-15 17:21 UTC, ShenyiCui commented on src/modules/subscription/types.ts
> +  accessRights: string[];
same as the comment mentioned in #21

2022-06-15 17:22 UTC, ShenyiCui commented on src/pages/Test/Test.tsx
> +  accessRights: ['Admin', 'Teacher'],
Same as #21 comment regarding creating a constant for Roles

2022-06-15 17:24 UTC, ShenyiCui commented on src/pages/Test/Test.tsx
> +  expiry: '2023-06-01',
@jasonqiu212  will push a fix later for the expiry date. The date it accepts now will be slightly different. Ask @jasonqiu212 for the new date requirements in the backend and make the necessary changes

2022-06-15 17:25 UTC, ShenyiCui requested changes
sorry, i accidentally approved it, please make the required changes first, thanks!

2022-06-23 02:15 UTC, jasonqiu212 requested changes
some minor comments! 

as for the type of the datetime, i'm not too sure if using type `Moment` is the way to go. Since ultimately, when you pass the date to the backend, it will converted into a string. I was thinking of creating a custom `dateString` type to handle this. lemme consult with Shenyi

2022-06-26 11:46 UTC, merged